"""initial tabels

Revision ID: 0001
Revises:
Create Date: 2026-05-30 17:13:46.612240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Создаёт начальную схему БД для профилей туторов и связанных сущностей."""
    op.execute(
        sa.text(
            """
            CREATE TYPE tutor_work_format AS ENUM (
                'online',
                'offline',
                'hybrid'
            );

            CREATE TYPE tutor_level AS ENUM (
                'A1',
                'A2',
                'B1',
                'B2',
                'C1',
                'C2'
            );

            CREATE TYPE tutor_status AS ENUM (
                'draft',
                'unvisible',
                'moderation',
                'approved',
                'rejected'
            );

            CREATE TABLE tutors (
                id UUID PRIMARY KEY,
                description TEXT NOT NULL,
                cities TEXT[] NOT NULL,
                levels tutor_level[] NOT NULL,
                price INTEGER NOT NULL CHECK (price > 0),
                lesson_duration INTEGER NOT NULL CHECK (lesson_duration > 0),
                work_format tutor_work_format NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE tags (
                name TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE contacts (
                tutor_id UUID NOT NULL REFERENCES tutors (id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                value TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (tutor_id, name)
            );

            CREATE TABLE achievements (
                tutor_id UUID NOT NULL REFERENCES tutors (id) ON DELETE CASCADE,
                image TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (tutor_id, image)
            );

            CREATE TABLE profile_tags (
                tutor_id UUID NOT NULL REFERENCES tutors (id) ON DELETE CASCADE,
                tag_name TEXT NOT NULL REFERENCES tags (name) ON DELETE CASCADE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (tutor_id, tag_name)
            );

            CREATE TABLE status_history (
                id UUID PRIMARY KEY,
                tutor_id UUID NOT NULL REFERENCES tutors (id) ON DELETE CASCADE,
                status tutor_status NOT NULL,
                seq INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (tutor_id, seq)
            );

            CREATE INDEX status_history_tutor_id_seq_idx
                ON status_history (tutor_id, seq);

            CREATE TABLE videos (
                tutor_id UUID PRIMARY KEY REFERENCES tutors (id) ON DELETE CASCADE,
                video TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE points (
                id UUID PRIMARY KEY,
                tutor_id UUID NOT NULL REFERENCES tutors (id) ON DELETE CASCADE,
                text TEXT NOT NULL,
                seq INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (tutor_id, seq)
            );

            CREATE INDEX points_tutor_id_seq_idx
                ON points (tutor_id, seq);
            """
        )
    )


def downgrade() -> None:
    """Откатывает начальную схему БД."""
    op.execute(
        sa.text(
            """
            DROP TABLE IF EXISTS points;
            DROP TABLE IF EXISTS videos;
            DROP TABLE IF EXISTS status_history;
            DROP TABLE IF EXISTS profile_tags;
            DROP TABLE IF EXISTS achievements;
            DROP TABLE IF EXISTS contacts;
            DROP TABLE IF EXISTS tags;
            DROP TABLE IF EXISTS tutors;

            DROP TYPE IF EXISTS tutor_status;
            DROP TYPE IF EXISTS tutor_level;
            DROP TYPE IF EXISTS tutor_work_format;
            """
        )
    )
